# Generated by Django 5.2.2 on 2025-06-07 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PricingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('base_distance_km', models.FloatField()),
                ('base_price_inr', models.FloatField()),
                ('additional_price_per_km', models.FloatField()),
                ('free_waiting_time_min', models.IntegerField(default=3)),
                ('waiting_charge_per_3_min', models.FloatField(default=5.0)),
                ('time_multipliers', models.JSONField()),
                ('days_applicable', models.CharField(help_text='Comma-separated days (e.g. mon,tue,wed)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
